...

diff --git a/v0 b/v0
--- a/v0
+++ b/v0
@@ -33,27 +33,25 @@ ___x_cmd_install_run(){
         -y|--yes)       YES=1; shift
     esac
 
-    for i in "$@"; do
-        local target
-        if target="$(___x_cmd_install_get "${1:?Provide target}")"; then
-            printf "Executing command:\n> \e[32;1m%s\e[0m\n\n" "$target" >&2
-            if [ -n "$YES" ]; then
-                eval "$target"
-                return
-            fi
-
-            printf "Do you want to continue? Press y to continue, otherwise will abort: " >&2
-            local ch
-            read -r ch
-            if [ "$ch" = y ]; then
-                eval "$target"
-            else
-                printf "Abort becase received non y\n" >&2
-                return 1
-            fi
+    local target
+    if target="$(___x_cmd_install_get "${1:?Provide target}")"; then
+        printf "Executing command:\n> \e[32;1m%s\e[0m\n\n" "$target" >&2
+        if [ -n "$YES" ]; then
+            eval "$target"
+            return
         fi
-        shift
-    done
+
+        printf "Do you want to continue? Press y to continue, otherwise will abort: " >&2
+        local ch
+        read -r ch
+        if [ "$ch" = y ]; then
+            eval "$target"
+        else
+            printf "Abort becase received non y\n" >&2
+            return 1
+        fi
+    fi
+    shift
 }
 
 ___x_cmd_install_which(){
